# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy the relevant files
COPY pyproject.toml main.py ./

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir mcp[cli]>=1.6.0 openai>=1.71.0

# Expose port if needed (not required for stdio transport)

# Run the MCP server
CMD ["python", "main.py"]
